[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/dlc-download"
  to = "/.netlify/functions/dlc-download"
  status = 200

[[redirects]]
  from = "/dlc-summary"
  to = "/.netlify/functions/summary-db"
  status = 200

[[redirects]]
  from = "/env-check"
  to = "/.netlify/functions/env-check"
  status = 200

[[redirects]]
  from = "/menu_dlc/regions.html"
  to = "/menu_dlc/contents.html"
  status = 301

[[redirects]]
  from = "/menu_dlc/events.html"
  to = "/menu_dlc/contents.html"
  status = 301
